/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 eBridgeDemo_theThing.glb -k -K -E --meta --shadows 
*/

import React from 'react'
import { useGLTF, PerspectiveCamera, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/eBridgeDemo_theThing.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        name="Scene"
        userData={{
          booltron: {},
          gltf_action_filter: [
            { keep: 1, action: { name: 'Assembly_Action', type: 'Action' } },
            { keep: 1, action: { name: 'Bottom_Hidden_Action', type: 'Action' } },
            { keep: 1, action: { name: 'BusinessCard_flip_Action', type: 'Action' } },
            { keep: 1, action: { name: 'BusinessCard_followDrawer_Action', type: 'Action' } },
            { keep: 1, action: { name: 'Config_Top_Action', type: 'Action' } },
            { keep: 1, action: { name: 'ConfigCamera_Action', type: 'Action' } },
          ],
        }}>
        <group name="Scene_Collection" userData={{ name: 'Scene Collection' }}>
          <group name="Cameras" userData={{ name: 'Cameras' }}>
            <group name="LiveMetricsCam_Target_EMPTY" position={[0.424, 1.477, -0.003]} userData={{ name: 'LiveMetricsCam_Target_EMPTY' }} />
            <group name="OverviewCam_Target_EMPTY" position={[-0.014, 0.93, 0.875]} userData={{ name: 'OverviewCam_Target_EMPTY' }} />
            <group name="OverviewCam_Position_EMPTY" position={[-1.048, 11.208, 3.353]} userData={{ name: 'OverviewCam_Position_EMPTY', fov: 50 }} />
            <group name="DemoMenuCam_Target_EMPTY" position={[-3.109, 0.403, -0.19]} userData={{ name: 'DemoMenuCam_Target_EMPTY' }} />
            <group name="DemoMenuCam_Position_EMPTY" position={[-3.47, 4.619, 4.916]} userData={{ name: 'DemoMenuCam_Position_EMPTY', fov: 50 }} />
            <group name="PowerButtonCam_Target_EMPTY" position={[1.184, 0.735, 1.587]} userData={{ name: 'PowerButtonCam_Target_EMPTY' }} />
            <group name="PowerButtonCam_Position_EMPTY" position={[2.617, 1.936, 2.996]} userData={{ name: 'PowerButtonCam_Position_EMPTY', fov: 50 }} />
            <group name="LiveMetricsCam_Position_EMPTY" position={[12.039, -0.346, -5.89]} userData={{ name: 'LiveMetricsCam_Position_EMPTY', fov: 221 }} />
            <group name="ScaleCam_Target_EMPTY" position={[1.572, 0.357, -1.599]} userData={{ name: 'ScaleCam_Target_EMPTY' }} />
            <group name="ScaleCam_Position_EMPTY" position={[1.626, 0.359, -2.084]} userData={{ name: 'ScaleCam_Position_EMPTY', fov: 50 }} />
            <group name="ConfigCam_Position_EMPTY" position={[0.052, 7.316, -2.42]} userData={{ name: 'ConfigCam_Position_EMPTY' }} />
            <group name="ConfigCam_Target_EMPTY" position={[-0.576, 0.511, 1.62]} rotation={[0, 0.221, 0]} userData={{ name: 'ConfigCam_Target_EMPTY' }} />
            <PerspectiveCamera name="_DemoMenu_Camera_1" makeDefault={false} far={100} near={0.1} fov={22.895} position={[-3.47, 4.619, 4.916]} rotation={[-0.69, -0.055, -0.045]} userData={{ name: '_DemoMenu_Camera' }} />
            <PerspectiveCamera name="_LiveMetrics_Camera_1" makeDefault={false} far={1000} near={0.1} fov={5.246} position={[12.039, -0.346, -5.89]} rotation={[2.841, 1.083, -2.875]} userData={{ name: '_LiveMetrics_Camera' }} />
            <PerspectiveCamera name="_Scale_Camera_1" makeDefault={false} far={1000} near={0.1} fov={22.895} position={[1.626, 0.359, -2.084]} rotation={[-3.138, 0.11, 3.141]} userData={{ name: '_Scale_Camera' }} />
            <PerspectiveCamera name="_PowerButton_Camera_1" makeDefault={false} far={1000} near={0.1} fov={22.895} position={[2.617, 1.936, 2.996]} rotation={[-0.706, 0.659, 0.481]} userData={{ name: '_PowerButton_Camera' }} />
            <PerspectiveCamera name="_Overview_Camera_1" makeDefault={false} far={1000} near={0.1} fov={22.895} position={[1.45, 6.075, 8.08]} rotation={[-0.62, 0.164, 0.116]} userData={{ name: '_Overview_Camera' }} />
            <PerspectiveCamera name="_Assembly_Camera_1" makeDefault={false} far={1000} near={0.1} fov={39.761} position={[0, 9.925, 0]} rotation={[-Math.PI / 2, 0, 0]} userData={{ name: '_Assembly_Camera' }} />
            <PerspectiveCamera name="_Config_Camera_1" makeDefault={false} far={1000} near={0.1} fov={22.895} position={[0.052, 3.402, 3.656]} rotation={[-1.04, 0.167, 0.275]} userData={{ name: '_Config_Camera' }} />
          </group>
          <group name="THE_THING" userData={{ name: 'THE_THING' }}>
            <group name="Module_MainBody" userData={{ name: 'Module_MainBody' }}>
              <group name="mainBody" userData={{ name: 'mainBody' }}>
                <mesh name="mainBody_1" castShadow receiveShadow geometry={nodes.mainBody_1.geometry} material={materials.mainBody} />
                <mesh name="mainBody_2" castShadow receiveShadow geometry={nodes.mainBody_2.geometry} material={materials.mainBodyGrooveLights} />
                <mesh name="mainBody_3" castShadow receiveShadow geometry={nodes.mainBody_3.geometry} material={materials.liveDataLight} />
                <group name="dataPort" userData={{ name: 'dataPort' }}>
                  <mesh name="dataPort_1" castShadow receiveShadow geometry={nodes.dataPort_1.geometry} material={materials.mainBody} />
                  <mesh name="dataPort_2" castShadow receiveShadow geometry={nodes.dataPort_2.geometry} material={materials.dataCable} />
                </group>
              </group>
              <group name="powerButtonBorder" userData={{ name: 'powerButtonBorder' }}>
                <mesh name="powerButtonBorder_1" castShadow receiveShadow geometry={nodes.powerButtonBorder_1.geometry} material={materials.buttonBorder} />
                <mesh name="powerButtonBorder_2" castShadow receiveShadow geometry={nodes.powerButtonBorder_2.geometry} material={materials.socketBlack} />
                <mesh name="powerButton" castShadow receiveShadow geometry={nodes.powerButton.geometry} material={materials.powerButton} morphTargetDictionary={nodes.powerButton.morphTargetDictionary} morphTargetInfluences={nodes.powerButton.morphTargetInfluences} userData={{ targetNames: ['Key 1'], name: 'powerButton' }} />
                <mesh name="powerButtonIOLights" castShadow receiveShadow geometry={nodes.powerButtonIOLights.geometry} material={materials.mainScreenIOLights} userData={{ name: 'powerButtonIOLights' }} />
              </group>
              <group name="mainScreenPort_A" userData={{ name: 'mainScreenPort_A' }}>
                <mesh name="mainScreenPort_A_1" castShadow receiveShadow geometry={nodes.mainScreenPort_A_1.geometry} material={materials.buttonBorder} />
                <mesh name="mainScreenPort_A_2" castShadow receiveShadow geometry={nodes.mainScreenPort_A_2.geometry} material={materials.socketBlack} />
                <mesh name="mainScreenIOLights" castShadow receiveShadow geometry={nodes.mainScreenIOLights.geometry} material={materials.mainScreenIOLights} position={[-0.215, 0.957, -0.133]} rotation={[-Math.PI, 0, 0]} scale={[-0.033, -1, -0.127]} userData={{ name: 'mainScreenIOLights' }} />
              </group>
              <mesh name="returnToMenu_liveMetrics" castShadow receiveShadow geometry={nodes.returnToMenu_liveMetrics.geometry} material={materials.returnToMenuLights} userData={{ name: 'returnToMenu_liveMetrics' }} />
              <group name="modeSelectorButton" userData={{ name: 'modeSelectorButton' }}>
                <mesh name="modeSelectorButton_1" castShadow receiveShadow geometry={nodes.modeSelectorButton_1.geometry} material={materials.buttonBlack} />
                <mesh name="modeSelectorButton_2" castShadow receiveShadow geometry={nodes.modeSelectorButton_2.geometry} material={materials.mainBodyGrooveLights} />
              </group>
              <group name="configurationModeButton" position={[-0.736, 0, 0.208]} userData={{ name: 'configurationModeButton' }}>
                <mesh name="configurationModeButton_1" castShadow receiveShadow geometry={nodes.configurationModeButton_1.geometry} material={materials.buttonBlack} />
                <mesh name="configurationModeButton_2" castShadow receiveShadow geometry={nodes.configurationModeButton_2.geometry} material={materials.decal_blue} />
                <mesh name="configurationDecal_ActiveOnly" castShadow receiveShadow geometry={nodes.configurationDecal_ActiveOnly.geometry} material={nodes.configurationDecal_ActiveOnly.material} position={[1.18, 0.961, -1.888]} userData={{ name: 'configurationDecal_ActiveOnly' }} />
                <mesh name="configurationDecal_Persistent" castShadow receiveShadow geometry={nodes.configurationDecal_Persistent.geometry} material={nodes.configurationDecal_Persistent.material} position={[1.322, 0.961, -1.888]} userData={{ name: 'configurationDecal_Persistent' }} />
                <mesh name="configurationModeSelectorBase" castShadow receiveShadow geometry={nodes.configurationModeSelectorBase.geometry} material={materials.mainBody} position={[1.251, 0.952, -1.794]} userData={{ name: 'configurationModeSelectorBase' }}>
                  <mesh name="configurationModeLED_ACTIVE_ONLY" castShadow receiveShadow geometry={nodes.configurationModeLED_ACTIVE_ONLY.geometry} material={materials.configurationModeLED} position={[-0.071, 0.011, -0.009]} userData={{ name: 'configurationModeLED_ACTIVE_ONLY' }} />
                  <mesh name="configurationModeLED_PERSISTENT" castShadow receiveShadow geometry={nodes.configurationModeLED_PERSISTENT.geometry} material={materials.configurationModeLED} position={[-0.587, -0.952, 1.586]} userData={{ name: 'configurationModeLED_PERSISTENT' }} />
                </mesh>
              </group>
              <mesh name="mainBody_consensusReachedButton" castShadow receiveShadow geometry={nodes.mainBody_consensusReachedButton.geometry} material={materials.liveDataLight} userData={{ name: 'mainBody_consensusReachedButton' }} />
            </group>
            <group name="Top_HiddenPanel" userData={{ name: 'Top_HiddenPanel' }}>
              <group name="topHiddenPanel_A" userData={{ name: 'topHiddenPanel_A' }}>
                <mesh name="topHiddenPanel_A_1" castShadow receiveShadow geometry={nodes.topHiddenPanel_A_1.geometry} material={materials.mainBody} />
                <mesh name="topHiddenPanel_A_2" castShadow receiveShadow geometry={nodes.topHiddenPanel_A_2.geometry} material={materials.topHidden_screenBlack} />
                <mesh name="topHiddenPanel_A_3" castShadow receiveShadow geometry={nodes.topHiddenPanel_A_3.geometry} material={materials.mainBodyGrooveLights} />
                <mesh name="topHidden_screen" castShadow receiveShadow geometry={nodes.topHidden_screen.geometry} material={materials.topHidden_screen} position={[0, 0, 1.079]} userData={{ name: 'topHidden_screen' }} />
              </group>
            </group>
            <group name="Module_DemoScreen" userData={{ name: 'Module_DemoScreen' }}>
              <group name="demoScreenBase_A" userData={{ name: 'demoScreenBase_A' }}>
                <mesh name="demoScreenBase_A_1" castShadow receiveShadow geometry={nodes.demoScreenBase_A_1.geometry} material={materials.mainBody} />
                <mesh name="demoScreenBase_A_2" castShadow receiveShadow geometry={nodes.demoScreenBase_A_2.geometry} material={materials.demoScreenBG} />
                <mesh name="demoScreenGlass" castShadow receiveShadow geometry={nodes.demoScreenGlass.geometry} material={materials.demoScreenGlass} userData={{ name: 'demoScreenGlass' }}>
                  <mesh name="demoScreenTextPlane" castShadow receiveShadow geometry={nodes.demoScreenTextPlane.geometry} material={materials.demoScreenGlass} userData={{ name: 'demoScreenTextPlane' }} />
                </mesh>
              </group>
            </group>
            <group name="Module_UIButtons" userData={{ name: 'Module_UIButtons' }}>
              <group name="uiButtonsBorder" userData={{ name: 'uiButtonsBorder' }}>
                <mesh name="uiButtonsBorder_1" castShadow receiveShadow geometry={nodes.uiButtonsBorder_1.geometry} material={materials.buttonBorder} />
                <mesh name="uiButtonsBorder_2" castShadow receiveShadow geometry={nodes.uiButtonsBorder_2.geometry} material={materials.socketBlack} />
                <mesh name="uiButton_1" castShadow receiveShadow geometry={nodes.uiButton_1.geometry} material={materials.uiButton_1} morphTargetDictionary={nodes.uiButton_1.morphTargetDictionary} morphTargetInfluences={nodes.uiButton_1.morphTargetInfluences} userData={{ targetNames: ['Key 1'], name: 'uiButton_1' }} />
                <mesh name="uiButton_2" castShadow receiveShadow geometry={nodes.uiButton_2.geometry} material={materials.uiButton_2} morphTargetDictionary={nodes.uiButton_2.morphTargetDictionary} morphTargetInfluences={nodes.uiButton_2.morphTargetInfluences} userData={{ targetNames: ['Key 1'], name: 'uiButton_2' }} />
                <mesh name="uiButton_3" castShadow receiveShadow geometry={nodes.uiButton_3.geometry} material={materials.uiButton_3} morphTargetDictionary={nodes.uiButton_3.morphTargetDictionary} morphTargetInfluences={nodes.uiButton_3.morphTargetInfluences} userData={{ targetNames: ['Key 1'], name: 'uiButton_3' }} />
              </group>
              <mesh name="uiButtonsIOLights" castShadow receiveShadow geometry={nodes.uiButtonsIOLights.geometry} material={materials.mainScreenIOLights} position={[1.093, 0.965, 0.309]} rotation={[0, 0, -Math.PI]} scale={[-0.074, -1, -0.02]} userData={{ name: 'uiButtonsIOLights' }} />
            </group>
            <group name="Bottom_HiddenDrawer" userData={{ name: 'Bottom_HiddenDrawer' }}>
              <group name="bottomHiddenDrawer_A" userData={{ name: 'bottomHiddenDrawer_A' }}>
                <mesh name="bottomHiddenDrawer_A_1" castShadow receiveShadow geometry={nodes.bottomHiddenDrawer_A_1.geometry} material={materials.mainBody} />
                <mesh name="bottomHiddenDrawer_A_2" castShadow receiveShadow geometry={nodes.bottomHiddenDrawer_A_2.geometry} material={materials.dataPort} />
                <mesh name="bottomHiddenDrawer_A_3" castShadow receiveShadow geometry={nodes.bottomHiddenDrawer_A_3.geometry} material={materials.liveDataLight} />
                <mesh name="bottomHiddenDrawer_A_4" castShadow receiveShadow geometry={nodes.bottomHiddenDrawer_A_4.geometry} material={materials.businessCard} />
                <group name="CardEMPTY" position={[-0.576, 0.511, 1.532]} userData={{ name: 'CardEMPTY' }} />
              </group>
              <mesh name="businessCard" castShadow receiveShadow geometry={nodes.businessCard.geometry} material={materials.businessCard} position={[-0.576, 0.53, 1.602]} rotation={[0, 0.221, 0]} userData={{ name: 'businessCard' }} />
            </group>
            <group name="Module_DemoButtons" userData={{ name: 'Module_DemoButtons' }}>
              <mesh name="demoButton_1" castShadow receiveShadow geometry={nodes.demoButton_1.geometry} material={materials.demoButton_1} morphTargetDictionary={nodes.demoButton_1.morphTargetDictionary} morphTargetInfluences={nodes.demoButton_1.morphTargetInfluences} position={[-1.533, 0.406, -0.973]} userData={{ targetNames: ['Key 1'], name: 'demoButton_1' }} />
              <mesh name="demoButton_2" castShadow receiveShadow geometry={nodes.demoButton_2.geometry} material={materials.demoButton_2} morphTargetDictionary={nodes.demoButton_2.morphTargetDictionary} morphTargetInfluences={nodes.demoButton_2.morphTargetInfluences} position={[-1.533, 0.406, -0.476]} userData={{ targetNames: ['Key 1'], name: 'demoButton_2' }} />
              <mesh name="demoButtonsBorder_2only" castShadow receiveShadow geometry={nodes.demoButtonsBorder_2only.geometry} material={materials.socketBlack} userData={{ name: 'demoButtonsBorder_2only' }} />
            </group>
            <group name="DemoTexts" userData={{ name: 'DemoTexts' }}>
              <mesh name="demoText_live_metrics" castShadow receiveShadow geometry={nodes.demoText_live_metrics.geometry} material={materials.live_metrics} userData={{ name: 'demoText_live_metrics' }} />
              <mesh name="demoText_configuration" castShadow receiveShadow geometry={nodes.demoText_configuration.geometry} material={materials.configuration} position={[-1.802, 0.403, -0.691]} userData={{ name: 'demoText_configuration' }} />
            </group>
            <group name="LiveMetrics" userData={{ name: 'LiveMetrics' }}>
              <mesh name="liveMetricBar_3" castShadow receiveShadow geometry={nodes.liveMetricBar_3.geometry} material={materials.Material} position={[-0.001, 1.098, -0.57]} userData={{ name: 'liveMetricBar_3' }} />
              <mesh name="liveMetricBar_1" castShadow receiveShadow geometry={nodes.liveMetricBar_1.geometry} material={materials.Material} position={[-0.001, 1.098, 0.303]} userData={{ name: 'liveMetricBar_1' }} />
              <mesh name="liveMetricBar_2" castShadow receiveShadow geometry={nodes.liveMetricBar_2.geometry} material={materials.Material} position={[-0.001, 1.098, -0.134]} userData={{ name: 'liveMetricBar_2' }} />
            </group>
            <group name="Scale" userData={{ name: 'Scale' }}>
              <mesh name="mainBodyGrooveRails" castShadow receiveShadow geometry={nodes.mainBodyGrooveRails.geometry} material={materials.scaleRails} position={[0, 0.017, 0]} userData={{ name: 'mainBodyGrooveRails' }} />
            </group>
          </group>
          <group name="Lights" userData={{ name: 'Lights' }}>
            <group name="menu_pinLight_Target_EMPTY" position={[-1.375, 0.616, -0.04]} userData={{ name: 'menu_pinLight_Target_EMPTY' }} />
            <group name="liveMetrics_pinLight_Target_EMPTY" position={[1.473, 1.292, -0.348]} userData={{ name: 'liveMetrics_pinLight_Target_EMPTY' }} />
            <group name="Empty" position={[0.444, 0.936, -1.595]} userData={{ name: 'Empty' }} />
            <group name="Empty001" position={[-1.802, 0.403, -0.691]} userData={{ name: 'Empty.001' }} />
            <group name="Empty002" position={[-1.802, 0.403, -0.205]} userData={{ name: 'Empty.002' }} />
            <pointLight name="menu_pinLight" intensity={81398.1} decay={2} color="#90b6ff" position={[-0.658, 1.65, -2.358]} rotation={[-2.722, 0.275, 3.021]} userData={{ name: 'menu_pinLight' }} />
            <pointLight name="liveMetrics_pinLight" intensity={26452.83} decay={2} color="#98b0ff" position={[3.974, 1.672, -0.618]} rotation={[-2.187, 1.387, 2.195]} userData={{ name: 'liveMetrics_pinLight' }} />
            <pointLight name="assembly_pinLight_fill" intensity={2608.868} decay={2} color="#c4ffa7" position={[3.869, 3.788, -2.446]} rotation={[-Math.PI / 2, 0, 0]} userData={{ name: 'assembly_pinLight_fill' }} />
          </group>
          <group name="BG_Extras" userData={{ name: 'BG_Extras' }}>
            <group name="underMainBodyCloud_point" position={[0.4, -1.619, -0.681]} userData={{ name: 'underMainBodyCloud_point' }} />
            <mesh name="menu_bg_strip" castShadow receiveShadow geometry={nodes.menu_bg_strip.geometry} material={materials.menu_bg_strip} userData={{ name: 'menu_bg_strip' }} />
            <mesh name="liveMetrics_bg_panel" castShadow receiveShadow geometry={nodes.liveMetrics_bg_panel.geometry} material={materials.liveMetrics_bg_panel} userData={{ name: 'liveMetrics_bg_panel' }} />
          </group>
          <group name="Decals" userData={{ name: 'Decals' }}>
            <mesh name="decal_10Mode" castShadow receiveShadow geometry={nodes.decal_10Mode.geometry} material={materials.decal_blue} position={[0.962, 0.935, -1.534]} userData={{ name: 'decal_10Mode' }} />
            <mesh name="decal_menu" castShadow receiveShadow geometry={nodes.decal_menu.geometry} material={materials.decal_blue} position={[1.547, 0.839, -0.915]} rotation={[1.571, 0.797, -Math.PI / 2]} scale={0.128} userData={{ name: 'decal_menu' }} />
            <mesh name="decal_Power" castShadow receiveShadow geometry={nodes.decal_Power.geometry} material={materials.decal_blue} position={[0.881, 0.707, 1.22]} rotation={[Math.PI / 2, 0, 0]} scale={0.196} userData={{ name: 'decal_Power' }} />
            <mesh name="decal_Feel_the" castShadow receiveShadow geometry={nodes.decal_Feel_the.geometry} material={materials.decal_blue} position={[0.853, 0.722, 1.8]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.152} userData={{ name: 'decal_Feel_the' }} />
            <mesh name="decal_LOGO" castShadow receiveShadow geometry={nodes.decal_LOGO.geometry} material={materials.decal_blue} position={[-1.167, 0.94, -0.989]} rotation={[0.003, 0.489, 0]} scale={0.392} userData={{ name: 'decal_LOGO' }} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/eBridgeDemo_theThing.glb')
