/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 eBridgeDemo_theThing.glb -k -K -E 
*/

import React from 'react'
import { useGLTF, PerspectiveCamera, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/eBridgeDemo_theThing.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Scene_Collection">
          <group name="Cameras">
            <group name="LiveMetricsCam_Target_EMPTY" position={[0.424, 1.477, -0.003]} />
            <group name="OverviewCam_Target_EMPTY" position={[-0.014, 0.93, 0.875]} />
            <group name="OverviewCam_Position_EMPTY" position={[-1.048, 11.208, 3.353]} />
            <group name="DemoMenuCam_Target_EMPTY" position={[-3.109, 0.403, -0.19]} />
            <group name="DemoMenuCam_Position_EMPTY" position={[-3.47, 4.619, 4.916]} />
            <group name="PowerButtonCam_Target_EMPTY" position={[1.184, 0.735, 1.587]} />
            <group name="PowerButtonCam_Position_EMPTY" position={[2.617, 1.936, 2.996]} />
            <group name="LiveMetricsCam_Position_EMPTY" position={[12.039, -0.346, -5.89]} />
            <group name="ScaleCam_Target_EMPTY" position={[1.572, 0.357, -1.599]} />
            <group name="ScaleCam_Position_EMPTY" position={[1.626, 0.359, -2.084]} />
            <PerspectiveCamera name="_DemoMenu_Camera_1" makeDefault={false} far={100} near={0.1} fov={22.895} position={[-3.47, 4.619, 4.916]} rotation={[-0.69, -0.055, -0.045]} />
            <PerspectiveCamera name="_LiveMetrics_Camera_1" makeDefault={false} far={1000} near={0.1} fov={5.246} position={[12.039, -0.346, -5.89]} rotation={[2.841, 1.083, -2.875]} />
            <PerspectiveCamera name="_Scale_Camera_1" makeDefault={false} far={1000} near={0.1} fov={22.895} position={[1.626, 0.359, -2.084]} rotation={[-3.138, 0.11, 3.141]} />
            <PerspectiveCamera name="_PowerButton_Camera_1" makeDefault={false} far={1000} near={0.1} fov={22.895} position={[2.617, 1.936, 2.996]} rotation={[-0.706, 0.659, 0.481]} />
            <PerspectiveCamera name="_Overview_Camera_1" makeDefault={false} far={1000} near={0.1} fov={22.895} position={[1.45, 6.075, 8.08]} rotation={[-0.62, 0.164, 0.116]} />
            <PerspectiveCamera name="_Assembly_Camera_1" makeDefault={false} far={1000} near={0.1} fov={39.761} position={[0, 9.925, 0]} rotation={[-Math.PI / 2, 0, 0]} />
            <PerspectiveCamera name="_Config_Camera_1" makeDefault={false} far={1000} near={0.1} fov={22.895} position={[0.052, 7.316, -2.42]} rotation={[-Math.PI / 2, 0, 0]} />
            <PerspectiveCamera name="Camera_1" makeDefault={false} far={1000} near={0.1} fov={22.895} position={[-1.091, 3.662, 4.521]} rotation={[-0.76, -0.168, -0.158]} />
          </group>
          <group name="THE_THING">
            <group name="Module_MainBody">
              <group name="mainBody">
                <mesh name="mainBody_1" geometry={nodes.mainBody_1.geometry} material={materials.mainBody} />
                <mesh name="mainBody_2" geometry={nodes.mainBody_2.geometry} material={materials.mainBodyGrooveLights} />
                <mesh name="mainBody_3" geometry={nodes.mainBody_3.geometry} material={materials.liveDataLight} />
                <group name="dataPort">
                  <mesh name="dataPort_1" geometry={nodes.dataPort_1.geometry} material={materials.mainBody} />
                  <mesh name="dataPort_2" geometry={nodes.dataPort_2.geometry} material={materials.dataCable} />
                </group>
              </group>
              <group name="powerButtonBorder">
                <mesh name="powerButtonBorder_1" geometry={nodes.powerButtonBorder_1.geometry} material={materials.buttonBorder} />
                <mesh name="powerButtonBorder_2" geometry={nodes.powerButtonBorder_2.geometry} material={materials.socketBlack} />
                <mesh name="powerButton" geometry={nodes.powerButton.geometry} material={materials.powerButton} morphTargetDictionary={nodes.powerButton.morphTargetDictionary} morphTargetInfluences={nodes.powerButton.morphTargetInfluences} />
                <mesh name="powerButtonIOLights" geometry={nodes.powerButtonIOLights.geometry} material={materials.mainScreenIOLights} />
              </group>
              <group name="mainScreenPort_A">
                <mesh name="mainScreenPort_A_1" geometry={nodes.mainScreenPort_A_1.geometry} material={materials.buttonBorder} />
                <mesh name="mainScreenPort_A_2" geometry={nodes.mainScreenPort_A_2.geometry} material={materials.socketBlack} />
                <mesh name="mainScreenIOLights" geometry={nodes.mainScreenIOLights.geometry} material={materials.mainScreenIOLights} position={[-0.215, 0.957, -0.133]} rotation={[-Math.PI, 0, 0]} scale={[-0.033, -1, -0.127]} />
              </group>
              <mesh name="returnToMenu_liveMetrics" geometry={nodes.returnToMenu_liveMetrics.geometry} material={materials.returnToMenuLights} />
              <group name="modeSelectorButton">
                <mesh name="modeSelectorButton_1" geometry={nodes.modeSelectorButton_1.geometry} material={materials.buttonBlack} />
                <mesh name="modeSelectorButton_2" geometry={nodes.modeSelectorButton_2.geometry} material={materials.mainBodyGrooveLights} />
              </group>
              <group name="configurationModeButton" position={[-0.736, 0, 0.208]}>
                <mesh name="configurationModeButton_1" geometry={nodes.configurationModeButton_1.geometry} material={materials.buttonBlack} />
                <mesh name="configurationModeButton_2" geometry={nodes.configurationModeButton_2.geometry} material={materials.decal_blue} />
                <mesh name="configurationDecal_ActiveOnly" geometry={nodes.configurationDecal_ActiveOnly.geometry} material={nodes.configurationDecal_ActiveOnly.material} position={[1.394, 0.961, -1.888]} />
                <mesh name="configurationDecal_Persistent" geometry={nodes.configurationDecal_Persistent.geometry} material={nodes.configurationDecal_Persistent.material} position={[1.251, 0.961, -1.888]} />
                <mesh name="configurationDecal_Strict" geometry={nodes.configurationDecal_Strict.geometry} material={nodes.configurationDecal_Strict.material} position={[1.109, 0.961, -1.886]} />
                <mesh name="configurationModeSelectorBase" geometry={nodes.configurationModeSelectorBase.geometry} material={materials.mainBody} position={[0.736, 0, -0.208]}>
                  <mesh name="configurationModeLED_ACTIVE" geometry={nodes.configurationModeLED_ACTIVE.geometry} material={materials.configurationModeLED} />
                  <mesh name="configurationModeLED_PERSISTENT" geometry={nodes.configurationModeLED_PERSISTENT.geometry} material={materials.configurationModeLED} />
                  <mesh name="configurationModeLED_STRICT" geometry={nodes.configurationModeLED_STRICT.geometry} material={materials.configurationModeLED} />
                </mesh>
              </group>
            </group>
            <group name="Top_HiddenPanel">
              <group name="topHiddenPanel_A">
                <mesh name="topHiddenPanel_A_1" geometry={nodes.topHiddenPanel_A_1.geometry} material={materials.mainBody} />
                <mesh name="topHiddenPanel_A_2" geometry={nodes.topHiddenPanel_A_2.geometry} material={materials.topHidden_screenBlack} />
                <mesh name="topHiddenPanel_A_3" geometry={nodes.topHiddenPanel_A_3.geometry} material={materials.mainBodyGrooveLights} />
                <mesh name="topHidden_screen" geometry={nodes.topHidden_screen.geometry} material={materials.topHidden_screen} position={[0, 0, 1.079]} />
              </group>
            </group>
            <group name="Module_DemoScreen">
              <group name="demoScreenBase_A">
                <mesh name="demoScreenBase_A_1" geometry={nodes.demoScreenBase_A_1.geometry} material={materials.mainBody} />
                <mesh name="demoScreenBase_A_2" geometry={nodes.demoScreenBase_A_2.geometry} material={materials.demoScreenBG} />
                <mesh name="demoScreenGlass" geometry={nodes.demoScreenGlass.geometry} material={materials.demoScreenGlass}>
                  <mesh name="demoScreenTextPlane" geometry={nodes.demoScreenTextPlane.geometry} material={materials.demoScreenGlass} />
                </mesh>
              </group>
            </group>
            <group name="Module_UIButtons">
              <group name="uiButtonsBorder">
                <mesh name="uiButtonsBorder_1" geometry={nodes.uiButtonsBorder_1.geometry} material={materials.buttonBorder} />
                <mesh name="uiButtonsBorder_2" geometry={nodes.uiButtonsBorder_2.geometry} material={materials.socketBlack} />
                <mesh name="uiButton_1" geometry={nodes.uiButton_1.geometry} material={materials.uiButton_1} morphTargetDictionary={nodes.uiButton_1.morphTargetDictionary} morphTargetInfluences={nodes.uiButton_1.morphTargetInfluences} />
                <mesh name="uiButton_2" geometry={nodes.uiButton_2.geometry} material={materials.uiButton_2} morphTargetDictionary={nodes.uiButton_2.morphTargetDictionary} morphTargetInfluences={nodes.uiButton_2.morphTargetInfluences} />
                <mesh name="uiButton_3" geometry={nodes.uiButton_3.geometry} material={materials.uiButton_3} morphTargetDictionary={nodes.uiButton_3.morphTargetDictionary} morphTargetInfluences={nodes.uiButton_3.morphTargetInfluences} />
              </group>
              <mesh name="uiButtonsIOLights" geometry={nodes.uiButtonsIOLights.geometry} material={materials.mainScreenIOLights} position={[1.093, 0.965, 0.309]} rotation={[0, 0, -Math.PI]} scale={[-0.074, -1, -0.02]} />
            </group>
            <group name="Bottom_HiddenDrawer">
              <group name="bottomHiddenDrawer_A">
                <mesh name="bottomHiddenDrawer_A_1" geometry={nodes.bottomHiddenDrawer_A_1.geometry} material={materials.mainBody} />
                <mesh name="bottomHiddenDrawer_A_2" geometry={nodes.bottomHiddenDrawer_A_2.geometry} material={materials.dataPort} />
                <mesh name="bottomHiddenDrawer_A_3" geometry={nodes.bottomHiddenDrawer_A_3.geometry} material={materials.liveDataLight} />
                <group name="CardEMPTY" position={[-0.576, 0.511, 1.532]} />
              </group>
              <mesh name="businessCard" geometry={nodes.businessCard.geometry} material={nodes.businessCard.material} position={[-0.576, 0.511, 2.202]} rotation={[0, 0.221, 0]} />
            </group>
            <group name="Module_DemoButtons">
              <mesh name="demoButton_1" geometry={nodes.demoButton_1.geometry} material={materials.demoButton_1} morphTargetDictionary={nodes.demoButton_1.morphTargetDictionary} morphTargetInfluences={nodes.demoButton_1.morphTargetInfluences} position={[-1.533, 0.406, -0.973]} />
              <mesh name="demoButton_2" geometry={nodes.demoButton_2.geometry} material={materials.demoButton_2} morphTargetDictionary={nodes.demoButton_2.morphTargetDictionary} morphTargetInfluences={nodes.demoButton_2.morphTargetInfluences} position={[-1.533, 0.406, -0.476]} />
              <mesh name="demoButton_3" geometry={nodes.demoButton_3.geometry} material={materials.demoButton_3} morphTargetDictionary={nodes.demoButton_3.morphTargetDictionary} morphTargetInfluences={nodes.demoButton_3.morphTargetInfluences} position={[-1.533, 0.406, 0.02]} />
              <mesh name="demoButton_4" geometry={nodes.demoButton_4.geometry} material={materials.demoButton_4} morphTargetDictionary={nodes.demoButton_4.morphTargetDictionary} morphTargetInfluences={nodes.demoButton_4.morphTargetInfluences} position={[-1.533, 0.406, 0.517]} />
              <mesh name="demoButtonsBorder" geometry={nodes.demoButtonsBorder.geometry} material={materials.socketBlack} />
            </group>
            <group name="DemoTexts">
              <mesh name="demoText_live_metrics" geometry={nodes.demoText_live_metrics.geometry} material={materials.live_metrics} />
              <mesh name="demoText_assembly" geometry={nodes.demoText_assembly.geometry} material={materials.assembly} />
              <mesh name="demoText_configuration" geometry={nodes.demoText_configuration.geometry} material={materials.configuration} />
              <mesh name="demoText_scale" geometry={nodes.demoText_scale.geometry} material={materials.scale} />
            </group>
            <group name="LiveMetrics">
              <mesh name="liveMetricBar_3" geometry={nodes.liveMetricBar_3.geometry} material={materials.Material} position={[-0.001, 1.098, -0.57]} />
              <mesh name="liveMetricBar_1" geometry={nodes.liveMetricBar_1.geometry} material={materials.Material} position={[-0.001, 1.098, 0.303]} />
              <mesh name="liveMetricBar_2" geometry={nodes.liveMetricBar_2.geometry} material={materials.Material} position={[-0.001, 1.098, -0.134]} />
            </group>
            <group name="Scale">
              <mesh name="mainBodyGrooveRails" geometry={nodes.mainBodyGrooveRails.geometry} material={materials.scaleRails} position={[0, 0.017, 0]} />
            </group>
          </group>
          <group name="Lights">
            <group name="menu_pinLight_Target_EMPTY" position={[-1.375, 0.616, -0.04]} />
            <group name="liveMetrics_pinLight_Target_EMPTY" position={[1.473, 1.292, -0.348]} />
            <pointLight name="menu_pinLight" intensity={81398.1} decay={2} position={[-0.658, 1.65, -2.358]} rotation={[-2.722, 0.275, 3.021]} />
            <pointLight name="liveMetrics_pinLight" intensity={26452.83} decay={2} position={[3.974, 1.672, -0.618]} rotation={[-2.187, 1.387, 2.195]} />
            <pointLight name="assembly_pinLight_fill" intensity={2608.868} decay={2} position={[3.869, 3.788, -2.446]} rotation={[-Math.PI / 2, 0, 0]} />
          </group>
          <group name="BG_Extras">
            <group name="underMainBodyCloud_point" position={[0.4, -1.619, -0.681]} />
            <mesh name="menu_bg_strip" geometry={nodes.menu_bg_strip.geometry} material={materials.menu_bg_strip} />
            <mesh name="liveMetrics_bg_panel" geometry={nodes.liveMetrics_bg_panel.geometry} material={materials.liveMetrics_bg_panel} />
          </group>
          <group name="Decals">
            <mesh name="decal_10Mode" geometry={nodes.decal_10Mode.geometry} material={materials.decal_blue} position={[0.962, 0.935, -1.534]} />
            <mesh name="decal_menu" geometry={nodes.decal_menu.geometry} material={materials.decal_blue} position={[1.547, 0.839, -0.915]} rotation={[1.571, 0.797, -Math.PI / 2]} scale={0.128} />
            <mesh name="decal_Power" geometry={nodes.decal_Power.geometry} material={materials.decal_blue} position={[0.881, 0.707, 1.22]} rotation={[Math.PI / 2, 0, 0]} scale={0.196} />
            <mesh name="decal_Feel_the" geometry={nodes.decal_Feel_the.geometry} material={materials.decal_blue} position={[0.853, 0.722, 1.8]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.152} />
            <mesh name="decal_LOGO" geometry={nodes.decal_LOGO.geometry} material={materials.decal_blue} position={[-1.167, 0.94, -0.989]} rotation={[0.003, 0.489, 0]} scale={0.392} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/eBridgeDemo_theThing.glb')
